### ISSUE TITLE
Dockerhub: Rebuild required?

### ISSUE THREAD

**Issue by Inego** [devillexio/docker-firebase#2]
Trying to deploy using the currently built image leads to the following:  

> HTTP Error: 410, This version of the Firebase CLI is no longer able to deploy to Firebase Hosting. Please upgrade to a newer version (>= 4.1.0).

**Comment by devilleweppenaar** [comment]
Thanks @Inego. Not entirely sure why the builds are no longer automatically triggered by updates on the [node](https://hub.docker.com/r/_/node/) repo. I have triggered a build on both the main branch as well as the slim version.

**Comment by devilleweppenaar** [comment]
Both builds completed successfully. Please try again.

<img width="837" alt="image" src="https://user-images.githubusercontent.com/11049609/48121748-6ef35e80-e27e-11e8-8a5c-74e5d77aa0f4.png">

**Comment by Inego** [comment]
The problem is gone.
Thank you!
