### ISSUE TITLE
Cypress problem

### ISSUE THREAD

**Issue by salime45** [devillexio/docker-firebase#4]
Hi

I am using this image for build my app in bitbucket, but i have a problema with Cypress.

Cypress cannot write to the cache directory due to file permissions

Someone now how to fix?

**Comment by devilleweppenaar** [comment]
I think you may be looking for one of the [official cypress images](https://hub.docker.com/u/cypress)?

**Comment by salime45** [comment]
Nop, the problem was folder without permisions for write the necesary thinks for Cypress , i fix it with chmod 777
