### ISSUE TITLE
New version of firebase-tools available

### ISSUE THREAD

**Issue by cpick** [devillexio/docker-firebase#5]
My deploy process has hit a bug that's fixed in the newer version of firebase-tools (v7.0.0).  For now I'm using my own rebuild of this image, but it be great to be able to switch back to your upstream version.  I was wondering if you could rebuild it?

Thanks for the useful image!

**Comment by devilleweppenaar** [comment]
Thanks for reporting this @cpick! I'll see what I can do.

**Comment by devilleweppenaar** [comment]
@cpick, can you please confirm whether this is also a problem on the latest build?

I currently have it [scheduled to rebuild](https://hub.docker.com/r/devillex/docker-firebase/builds) every week.

**Comment by cpick** [comment]
Latest build works great for me, thanks.
